[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_VERSION = "18"

# Define NODE_ENV for builds
[context.production.environment]
  NODE_ENV = "production"

# Handle Next.js routing
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Single redirect rule for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 