[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"

# Handle Next.js routing
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Redirects and rewrites
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["anonymous"]}

# For SPAs that handle their own routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 